### ISSUE TITLE
Some apps crash

### ISSUE THREAD

**Issue by sup3rgiu** [Legoless/Alpha#44]
Hi, 
Alpha is causing crashes in some apps. Can be a protection of the app? Though FlexLoader works fine

**Comment by OdNairy** [comment]
Can you catch crash exceptions? Crash report or stack trace from xcode.

**Comment by Legoless** [comment]
I am aware of the issue, and this is the top priority to fix. This is why I am also waiting with by officially putting out 0.2 milestone. Any crash logs would definitely be helpful a lot!

**Comment by sup3rgiu** [comment]
Here crash log and syslog:

http://ghostbin.com/paste/6zben
http://ghostbin.com/paste/h8uu8

**Comment by Legoless** [comment]
@sup3rgiu Is it possible that you get any more information on these crashes? Maybe what the exception was, exactly? From the logs you pasted, all I could see is:

```
Sat Jul 25 13:15:59 2015: Spotify (com.spotify.client): *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unable to load class BFTaskCompletionSource. Did you link Bolts.framework?'
```

This looks like something connected to Facebook SDK, not Alpha. Alpha does not use Bolts framework, but FB SDK does. Although it does happen after Alpha tries to swizzle `NSURLConnection` classes, but there is more code being executed afterwards, including `FBAppLinkResolver`, where the crash occurs.

**Comment by Legoless** [comment]
Closed due to inactivity.
