### ISSUE TITLE
Alpha pod: Unable to satisfy the following requirements

### ISSUE THREAD

**Issue by OdNairy** [Legoless/Alpha#59]
Current version of `Alpha.podspec` is not workable. The last right pod spec was 0.2.4. The next string is used in Podfile:
`pod 'Alpha', :git => "https://github.com/Legoless/Alpha.git", :tag => "0.2.6"`

**Comment by Legoless** [comment]
Hm, it is odd that CocoaPods does not specify the problem (even with using verbose parameter). The pod works, but I've finally specified correct platform (8.0) in the 0.2.6, so Alpha will now require platform to be iOS 8.0, when before it would let you install it on iOS 7.0. Supporting older iOS is not very high on priority list currently.

**Comment by OdNairy** [comment]
Well. I reproduced this issue on my iOS 7+ projects so the reason seams in iOS 7 support. 0.2.4 actually wasn't support iOS7 because of `-[UIScreen nativeScale]` method call (iOS 8+).
README says about iOS 8 support so it doesn't seems a Alpha issue. Hope iOS 8+ will remain for a long time.

**Comment by Legoless** [comment]
We'll keep iOS 8 support, but 0.2.4 still specified 7.0 in Podspec, that is why it "worked", but it was untested and unsupported, that is why it was properly removed in 0.2.6.

**Comment by OdNairy** [comment]
It's a right move since it was not actually working on iOS 7. It has been crash so the real iOS 7 support has gone a lot time ago.
