### ISSUE TITLE
Low Power Mode flag

### ISSUE THREAD

**Issue by urb4n** [Legoless/Alpha#62]
It would be nice also to have Low Power Mode flag which was introduced with iOS9.

`[[NSProcessInfo processInfo] isLowPowerModeEnabled]`

**Comment by urb4n** [comment]
https://developer.apple.com/library/prerelease/ios/documentation/Performance/Conceptual/EnergyGuide-iOS/LowPowerMode.html

**Comment by Legoless** [comment]
Will be added to Status plugin.

**Comment by Legoless** [comment]
Fixed in #e55db17.
